2025-06-19 02:53:10,344 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/css/base.css
2025-06-19 02:53:10,361 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:10,674 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:10,681 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/css/style.css
2025-06-19 02:53:10,685 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:10,992 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:10,998 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/css/bootstrap.css
2025-06-19 02:53:11,001 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:11,307 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:11,316 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/nregs_web-3.png
2025-06-19 02:53:11,328 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:11,601 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:11,606 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/saksham_tag3-3.png
2025-06-19 02:53:11,609 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:11,894 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:11,899 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/giz_web.png
2025-06-19 02:53:11,903 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:10,855 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:10,862 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/js/base.js
2025-06-19 02:53:10,872 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:11,139 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:11,143 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/js/bootstrap.bundle.js
2025-06-19 02:53:11,148 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:11,456 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:11,464 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/cropped-e-fv-192x192.png
2025-06-19 02:53:11,470 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:57,311 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:57,319 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/home
2025-06-19 02:53:57,323 [ERROR] in __init__: Payload: N/A
