2025-06-19 02:53:59,125 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:59,145 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/css/base.css
2025-06-19 02:53:59,149 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:59,448 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:59,464 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/css/style.css
2025-06-19 02:53:59,468 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:59,748 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:59,755 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/css/bootstrap.css
2025-06-19 02:53:59,759 [ERROR] in __init__: Payload: N/A
2025-06-19 02:54:00,078 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:54:00,086 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/nregs_web-3.png
2025-06-19 02:54:00,100 [ERROR] in __init__: Payload: N/A
2025-06-19 02:54:00,364 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:54:00,375 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/saksham_tag3-3.png
2025-06-19 02:54:00,381 [ERROR] in __init__: Payload: N/A
2025-06-19 02:54:00,676 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:54:00,696 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/giz_web.png
2025-06-19 02:54:00,704 [ERROR] in __init__: Payload: N/A
2025-06-19 02:54:01,052 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:54:01,059 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/js/base.js
2025-06-19 02:54:01,070 [ERROR] in __init__: Payload: N/A
2025-06-19 02:54:01,336 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:54:01,346 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/js/bootstrap.bundle.js
2025-06-19 02:54:01,350 [ERROR] in __init__: Payload: N/A
2025-06-19 02:54:01,669 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:54:01,682 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/cropped-e-fv-192x192.png
2025-06-19 02:54:01,688 [ERROR] in __init__: Payload: N/A
2025-06-19 03:03:04,652 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/routes/admin.py", line 107, in register
    user = User(name, email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__() missing 2 required positional arguments: 'is_active' and 'is_admin'
