2025-06-19 02:53:05,082 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:05,094 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/css/style.css
2025-06-19 02:53:05,100 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:05,372 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:05,385 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/css/bootstrap.css
2025-06-19 02:53:05,391 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:05,660 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:05,668 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/saksham_tag3-3.png
2025-06-19 02:53:05,674 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:05,952 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:05,959 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/nregs_web-3.png
2025-06-19 02:53:05,963 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:06,225 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:06,233 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/giz_web.png
2025-06-19 02:53:06,241 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:06,560 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:06,577 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/js/base.js
2025-06-19 02:53:06,582 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:06,898 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:06,905 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/js/bootstrap.bundle.js
2025-06-19 02:53:06,910 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:07,240 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:07,249 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/static/assets/cropped-e-fv-192x192.png
2025-06-19 02:53:07,254 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:09,926 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
2025-06-19 02:53:09,933 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/home
2025-06-19 02:53:09,937 [ERROR] in __init__: Payload: N/A
2025-06-19 02:53:10,336 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/__init__.py", line 111, in increment_visit_count
    db.rollback()  # Ensure the database session is clean before each request
    ^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 1008, in __getattr__
    raise AttributeError(name)
AttributeError: rollback
